version: 2.1
jobs:
  check_whitespace:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./dev-scripts/check-trailing-whitespace
      - run:
          name: Check that all text files end in a trailing newline
          command: ./dev-scripts/check-trailing-newline
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - run:
          name: Install dependencies needed to check out repo
          command: apk add bash git openssh-client grep
      - checkout
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
  check_frontend:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
          name: Download npm packages
          command: npm install
      - run:
          name: Check formatting
          command: ./dev-scripts/check-frontend-formatting
  test_go:
    docker:
      - image: cimg/go:1.20.4
    resource_class: medium
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - go-test-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Test go packages
          command: ./dev-scripts/run-go-tests
      - store_artifacts:
          path: .coverage.html
      - run:
          name: Verify golang formatting
          command: ./dev-scripts/check-go-formatting
      - save_cache:
          key: go-test-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
  build_backend:
    docker:
      - image: cimg/go:1.20.4
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Compile backend
          command: dev-scripts/build-backend
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
      - persist_to_workspace:
          root: ./
          paths:
            - ./bin/authboss-minimal
  e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.34.3-focal
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run e2e tests
          command: ./dev-scripts/run-e2e-tests --skip-build
      - store_artifacts:
          path: playwright-report
workflows:
  version: 2
  test_deploy:
    jobs:
      - check_whitespace
      - check_bash
      - check_frontend
      - build_backend
      - test_go
      - e2e:
          requires:
            - build_backend
